# Generated by Django 4.2.3 on 2023-07-28 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.customer'),
        ),
    ]
