# Generated by Django 4.2.3 on 2023-08-21 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ItemLiked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.item')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.customer')),
            ],
        ),
    ]
