# Generated by Django 4.2.3 on 2023-08-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_item_like_itemliked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='like',
            field=models.IntegerField(default=1),
        ),
    ]
