# Generated by Django 4.2.3 on 2023-10-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='itemPrice',
            field=models.IntegerField(default=126),
        ),
    ]
