# Generated by Django 4.2.3 on 2023-10-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_remove_item_price_item_itemprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemPrice',
            field=models.CharField(default='120', max_length=250),
        ),
    ]
